In [10]:
import numpy as np
import pandas as pd
from textblob import TextBlob 
import matplotlib.pyplot as plt   
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [13]:
df = pd.read_excel(r'C:\Users\rupab\OneDrive\Desktop\ML_PRACTICE\SENTIMENT\sentiment_dataset_1000.xlsx')

In [4]:
df.head()

,id,text,actual_label
0,1,The room has two windows,Neutral
1,2,Worth every penny,Positive
2,3,The package arrived today,Neutral
3,4,Delivery was very late,Negative
4,5,I bought a laptop,Neutral


In [14]:
df.info()
df.describe()
df.isnull().sum()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            1000 non-null   int64 
 1   text          1000 non-null   object
 2   actual_label  1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB


(1000, 3)

In [15]:
text = "Paradise movie is good"

In [16]:
sentiment = TextBlob(text).sentiment.polarity

In [17]:
print(sentiment)

0.7


In [18]:
text = "I am so happy today!"
sentiment = TextBlob(text).sentiment.polarity
print(sentiment)

1.0


In [19]:
def predict_sentiment(text):
    sentiment = TextBlob(text).sentiment.polarity
    if sentiment > 0:
        return "Positive"
    elif sentiment < 0:
        return "Negative"
    else:
        return "Neutral"
df['predicted_label'] = df['text'].apply(predict_sentiment)

In [20]:
df.head(10)

,id,text,actual_label,predicted_label
0,1,The room has two windows,Neutral,Neutral
1,2,Worth every penny,Positive,Positive
2,3,The package arrived today,Neutral,Neutral
3,4,Delivery was very late,Negative,Negative
4,5,I bought a laptop,Neutral,Neutral
5,6,Not worth the money,Negative,Negative
6,7,The package arrived today,Neutral,Neutral
7,8,Worst purchase ever,Negative,Negative
8,9,The weather is cloudy,Neutral,Neutral
9,10,Very bad quality,Negative,Negative


In [21]:
df['polarity'] = df['text'].apply(lambda x: TextBlob(x).sentiment.polarity)
df['subjectivity'] = df['text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

In [22]:
df.head()

,id,text,actual_label,predicted_label,polarity,subjectivity
0,1,The room has two windows,Neutral,Neutral,0.00,0.00
1,2,Worth every penny,Positive,Positive,0.30,0.10
2,3,The package arrived today,Neutral,Neutral,0.00,0.00
3,4,Delivery was very late,Negative,Negative,-0.39,0.78
4,5,I bought a laptop,Neutral,Neutral,0.00,0.00


In [23]:
accuracy = accuracy_score(df['actual_label'], df['predicted_label'])
print("Accuracy:", accuracy)    

Accuracy: 0.909


In [24]:
%pip install textblob

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
%pip install openpyxl


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
cm = confusion_matrix(df['actual_label'], df['predicted_label'])    

In [27]:
print(cm)

[[302  31   0]
 [  0 295  38]
 [  0  22 312]]


In [28]:
df.to_excel('Sentiment_Analysis_Results.xlsx', index=False)
print("Results saved to Sentiment_Analysis_Results.xlsx")

Results saved to Sentiment_Analysis_Results.xlsx
